### ISSUE TITLE
请删除未授权的《深入浅出程序设计竞赛》的文件

### ISSUE THREAD

**Issue by kkksc03** [rainboyOJ/problems#1]
https://d.roj.ac.cn/%E4%B9%A6%E7%B1%8D/OI%E7%AB%9E%E8%B5%9B%E7%9B%B8%E5%85%B3

我们未授权任何人公开图书内容，擅自公开是侵权行为。请予以删除，谢谢合作。

**Comment by Rainboylvx** [comment]
已删除
